### ISSUE TITLE
Create Initial Content Types

### ISSUE THREAD

**Issue by dmlb2000** [pacifica/pacifica-drupal-module-content#3]
### Pacifica Drupal Content module version
Master

### Pacifica Core Software versions
v1.0b

### Platform Details
Drupal 8.7.x with PHP 7.1+

### Scenario:
We are trying to use Drupal to model the Pacifica metadata and display content.

### Steps to Reproduce:
I enable the `pacifica_content` module and it doesn't contain any content types to build from.

### Expected Result:
Some basic content types to start building my Drupal website from.

Top Types:

 * Project (not sure on name)
 * Organization
 * Person
 * Data Set
 * Publication

Less Priority:

 * Data Set Group
 * Remote Data Set
 * Software
 * Data Source

Ontology should be present:

 * One closed ontology for each content type
 * Tags ontology that's open and user manupulation allowed
 * Categories that's closed and only manipulated by admins.

### Actual Result:
A lot of nothing.

**Comment by dmlb2000** [comment]
@jamesmarks Could you please create the content types and taxonomies described above in the https://github.com/pacifica/pacifica-userinterface-core install profile.

**Comment by hofmockel-zz** [comment]
These belong in the Core repository.
